CREATE TABLE vacancies.vacancy (
	id text NULL,
	"name" text NULL,
	area_name text NULL,
	experience_name text NULL,
	employer_name text NULL,
	response_url text NULL,
	specializations text NULL,
	professional_roles text NULL,
	published_at text NULL,
	working_days text NULL,
	salary_from int8 NULL,
	salary_to int8 NULL,
	salary_gross bool NULL,
	employment_name text NULL,
	address_raw text NULL,
	address_city text NULL,
	address_lat float8 NULL,
	address_lng float8 NULL,
	alternate_url text NULL,
	apply_alternate_url text NULL,
	archived bool NULL,
	load_date text NULL
);